Change uuid from code.google.com to github.com
The build mostly works after I changed in the imports for "code.google.com/p/go-uuid/uuid" to "github.com/pborman/uuid" (because code.google.com is going away).

But then I get this error from 'go get' and 'go build' when trying to build 'packer-builder-hyperv-iso'.

..\..\builder\hyperv\common\output_config.go:18: undefined: packer.ConfigTemplate

I think that type, ConfigTemplate, no longer exists in Packer ... It looks like it got removed in 0.8.0 (https://github.com/mitchellh/packer/commit/1d3a4d6aa2b2c969bb52f00e27113d21a28ad793)
... but I'm not sure what to do about it.

(I'm trying to get this building so I can then extend it to add Gen 2 support and "standard" edition support for 2012R2 servers.)